# Generated by Django 3.2 on 2021-04-15 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_usergeolocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='type',
        ),
        migrations.AddField(
            model_name='categorie',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.domaine'),
        ),
    ]
